layout_spectrum: 0.16082793823443353
typography_spectrum: 0.9717535623349249
color:
  brandStrength: 0.5294798212125897
  lightness: 0.516275463392958
  saturation: 0.4192888862453401
  rhythmicContrast: 0.7785790532361716
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Unfuckwithable
